export function cities(){

    return [
        { "name": "Baao", "province": "CAS" },
        { "name": "Balatan", "province": "CAS" },
        { "name": "Bato", "province": "CAS" },
        { "name": "Bombon", "province": "CAS" },
        { "name": "Buhi", "province": "CAS" },
        { "name": "Bula", "province": "CAS" },
        { "name": "Cabusao", "province": "CAS" },
        { "name": "Calabanga", "province": "CAS" },
        { "name": "Camaligan", "province": "CAS" },
        { "name": "Canaman", "province": "CAS" },
        { "name": "Caramoan", "province": "CAS" },
        { "name": "Del Gallego", "province": "CAS" },
        { "name": "Gainza", "province": "CAS" },
        { "name": "Garchitorena", "province": "CAS" },
        { "name": "Goa", "province": "CAS" },
        { "name": "Iriga", "province": "CAS", "city": true },
        { "name": "Lagonoy", "province": "CAS" },
        { "name": "Libmanan", "province": "CAS" },
        { "name": "Lupi", "province": "CAS" },
        { "name": "Magarao", "province": "CAS" },
        { "name": "Milaor", "province": "CAS" },
        { "name": "Minalabac", "province": "CAS" },
        { "name": "Nabua", "province": "CAS" },
        { "name": "Naga", "province": "CAS", "city": true },
        { "name": "Ocampo", "province": "CAS" },
        { "name": "Pamplona", "province": "CAS" },
        { "name": "Pasacao", "province": "CAS" },
        { "name": "Pili", "province": "CAS" },
        { "name": "Presentacion", "province": "CAS" },
        { "name": "Ragay", "province": "CAS" },
        { "name": "Sagñay", "province": "CAS" },
        { "name": "San Fernando", "province": "CAS" },
        { "name": "San Jose", "province": "CAS" },
        { "name": "Sipocot", "province": "CAS" },
        { "name": "Siruma", "province": "CAS" },
        { "name": "Tigaon", "province": "CAS" },
        { "name": "Tinambac", "province": "CAS" },
    ]
} 